// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.ComponentModel.DataAnnotations;

namespace Nether.Web.Features.PlayerManagement
{
    /// <summary>
    /// Player info request object
    /// </summary>
    public class PlayerPostRequestModel
    {
        /// <summary>
        /// Player ID. When ommited will be autogenerated.
        /// </summary>
        public string UserId { get; set; }
        /// <summary>
        /// Gamertag, must be uniqueue.
        /// </summary>
        [Required]
        public string Gamertag { get; set; }

        /// <summary>
        /// Country code
        /// </summary>
        public string Country { get; set; }

        /// <summary>
        /// Custom tag
        /// </summary>
        public string CustomTag { get; set; }
    }
}
